esphome:
  name: smart-station
  friendly_name: Smart Station

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "Deancjx-2.4ghz"
  password: "eralp123!"
  manual_ip:
    static_ip: 192.168.1.189
    gateway: 192.168.1.1
    subnet: 255.255.255.0

api:
  reboot_timeout: 0s

ota:
  platform: esphome

logger:
  level: DEBUG

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 30ms
    active: false

bluetooth_proxy:
  active: true
